// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	sys "cors-test/internal/handler/sys"
	"cors-test/internal/svc"

	"github.com/Holyson/test-go-zero-cors/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/test",
				Handler: sys.TestHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/weixin"),
	)
}
